name: Maven Simple Release
on:
  workflow_call:
    inputs:
      java-version:
        required: false
        default: '17'
        type: string
      java-distribution:
        required: false
        default: 'temurin'
        type: string
      settings-ref:
        required: false
        default: 'develop'
        type: string
    secrets:
      PACKAGES_READ_USER:
        description: The User name of the user owning read the Access Token
        required: true
      PACKAGES_READ_PAT:
        description: The Access Token, which allows read of private packages
        required: true
      PACKAGES_WRITE_USER:
        description: The User name of the user owning the write Access Token
        required: true
      PACKAGES_WITE_PAT:
        description: The Access Token, which allows write of private packages
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Maven Settings
        uses: actions/checkout@v2
        with:
          repository: 'medmera/maven-settings'
          ref: ${{ inputs.settings-ref }}
          path: 'maven-settings'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
          server-id: 'github'

      - name: Configure Git
        run: |
          git config user.name ${process.env.GITHUB_ACTOR}
          git config user.email "github-action@github.com"

      - name: Verify with Maven
        run: |
            mvn -B clean verify -s maven-settings/settings.xml
        env:
          MAVEN_USER: ${{ secrets.PACKAGES_READ_USER }}
          MAVEN_PASSWORD: ${{ secrets.PACKAGES_READ_PAT }}

      - name: Release
        run: |
          mvn -B gitflow:release -DargLine="-s maven-settings/settings.xml" -s maven-settings/settings.xml
        env:
          MAVEN_USER: ${{ secrets.PACKAGES_WRITE_USER }}
          MAVEN_PASSWORD: ${{ secrets.PACKAGES_WRITE_PAT }}

      - name: Push release
        run: |
          git push --all --follow-tags